Feature/gas filling stations filter with constant containing boundarys of southwest finland
City-of-Turku/smbackend pull request #218
Opened 2023-01-18 13:49 UTC by juuso-j

# Filter gas filling stations with a constant containing the boundaries of Southwest Finland

## Description
This hopefully also fixes the bug that gas filling stations filtering by location does not work in the production server.
As the geometry of Southwest Finland is no longer fetched during import and removed condition if pytest is loaded in
sys.modules. If pytest was loaded the filtering was discarded. 

-----------------------------------------------------------------------------------------------
### Breakdown:

#### Files changed
1. mobility_data/importers/gas_filling_station.py
     * Use constant with boundaries to filter by location.
2.  mobility_data/importers/constants.py
     * Add boundaries of Southwest Finland as a constant.
3. mobility_data/tests/data/gas_filling_stations.json
    * Add fixture data outside Southwest Finland.

2023-01-19 05:29 UTC, mhieta requested changes
Typo in comment. Looks good otherwise.

2023-01-19 05:29 UTC, mhieta commented on mobility_data/importers/gas_filling_station.py
> +    # Polygon used the detect if point intersects. i.e. is in the boundries of SouthWest Finland.
`boundries` --> `boundaries`

2023-01-19 07:52 UTC, juuso-j commented on mobility_data/importers/gas_filling_station.py
> +    # Polygon used the detect if point intersects. i.e. is in the boundries of SouthWest Finland.
Fixed

2023-01-23 10:50 UTC, ezkat approved these changes

2023-01-23 11:02 UTC, merged